export const sample_user = [
  {
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: true,
  },
  {
    name: 'Jane Doe',
    email: 'Jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: false,
  },
];
export const sample_deliverMessage: any[] = [
  {
    "id": 1,
    "sender": "John Doe",
    "receiver": "Jane Smith",
    "origin": "New York, NY",
    "destination": "Los Angeles, CA",
    "quantity": 1,
    "weight": "10kg",
    "length": "30cm",
    "width": "20cm",
    "height": "15cm",
    "material": "Plastic",
    "status": "運送中", // 修改为 "運送中"
    "trackingNumber": "AB123456789US",
    "createdAt": "2024-07-12T10:00:00Z"
  },
  {
    "id": 2,
    "sender": "Alice Johnson",
    "receiver": "Bob Brown",
    "origin": "Chicago, IL",
    "destination": "Houston, TX",
    "quantity": 2,
    "weight": "5kg",
    "length": "25cm",
    "width": "15cm",
    "height": "10cm",
    "material": "Metal",
    "status": "在倉庫",
    "trackingNumber": "CD987654321US",
    "createdAt": "2024-07-11T15:30:00Z"
  },
  {
    "id": 3,
    "sender": "Charlie Davis",
    "receiver": "Diana Evans",
    "origin": "San Francisco, CA",
    "destination": "Seattle, WA",
    "quantity": 3,
    "weight": "8kg",
    "length": "40cm",
    "width": "30cm",
    "height": "20cm",
    "material": "Wood",
    "status": "在倉庫",
    "trackingNumber": "EF123456789US",
    "createdAt": "2024-07-10T08:45:00Z"
  },
  {
    "id": 4,
    "sender": "Eve Foster",
    "receiver": "Frank Green",
    "origin": "Miami, FL",
    "destination": "Orlando, FL",
    "quantity": 4,
    "weight": "12kg",
    "length": "35cm",
    "width": "25cm",
    "height": "15cm",
    "material": "Glass",
    "status": "運送中", // 修改为 "運送中"
    "trackingNumber": "GH987654321US",
    "createdAt": "2024-07-09T18:20:00Z"
  },
  {
    "id": 5,
    "sender": "Grace Hall",
    "receiver": "Henry King",
    "origin": "Boston, MA",
    "destination": "Philadelphia, PA",
    "quantity": 5,
    "weight": "7kg",
    "length": "28cm",
    "width": "18cm",
    "height": "12cm",
    "material": "Paper",
    "status": "運送中",
    "trackingNumber": "IJ123456789US",
    "createdAt": "2024-07-08T12:10:00Z"
  },
  {
    "id": 6,
    "sender": "Ivy Lee",
    "receiver": "Jack Moore",
    "origin": "Dallas, TX",
    "destination": "Austin, TX",
    "quantity": 6,
    "weight": "9kg",
    "length": "32cm",
    "width": "22cm",
    "height": "16cm",
    "material": "Fabric",
    "status": "運送中",
    "trackingNumber": "KL987654321US",
    "createdAt": "2024-07-07T09:30:00Z"
  },
  {
    "id": 7,
    "sender": "Kyle Nelson",
    "receiver": "Lily Owens",
    "origin": "Phoenix, AZ",
    "destination": "Denver, CO",
    "quantity": 7,
    "weight": "11kg",
    "length": "37cm",
    "width": "27cm",
    "height": "17cm",
    "material": "Plastic",
    "status": "運送中", // 修改为 "運送中"
    "trackingNumber": "MN123456789US",
    "createdAt": "2024-07-06T14:45:00Z"
  },
  {
    "id": 8,
    "sender": "Mia Parker",
    "receiver": "Noah Quinn",
    "origin": "Las Vegas, NV",
    "destination": "Salt Lake City, UT",
    "quantity": 8,
    "weight": "6kg",
    "length": "29cm",
    "width": "19cm",
    "height": "13cm",
    "material": "Metal",
    "status": "在倉庫",
    "trackingNumber": "OP987654321US",
    "createdAt": "2024-07-05T11:20:00Z"
  },
  {
    "id": 9,
    "sender": "Olivia Roberts",
    "receiver": "Paul Scott",
    "origin": "San Diego, CA",
    "destination": "Portland, OR",
    "quantity": 9,
    "weight": "10kg",
    "length": "31cm",
    "width": "21cm",
    "height": "14cm",
    "material": "Wood",
    "status": "在倉庫",
    "trackingNumber": "QR123456789US",
    "createdAt": "2024-07-04T16:00:00Z"
  },
  {
    "id": 10,
    "sender": "Quinn Taylor",
    "receiver": "Ryan White",
    "origin": "Atlanta, GA",
    "destination": "Charlotte, NC",
    "quantity": 10,
    "weight": "8kg",
    "length": "33cm",
    "width": "23cm",
    "height": "15cm",
    "material": "Glass",
    "status": "在倉庫",
    "trackingNumber": "ST987654321US",
    "createdAt": "2024-07-03T20:30:00Z"
  }
];
